# Generated by Django 3.2 on 2023-05-25 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_book.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='None.jpg', upload_to=phone_book.models.avatar_uploadTo, verbose_name='آواتار')),
                ('alt', models.CharField(blank=True, default='', help_text='اگر تصویر به هر دلیل ممکن لود نشود این متن به جای تصویر نمایش داده خواهد شد', max_length=255, null=True, verbose_name='متن جایگزین تصویر')),
                ('status', models.BooleanField(default=True, help_text='مشخص کنید در صورت فعال بودن قابل انتخاب خواهد بود برای خارج کردن از دسترس غیر فعال نمایید', verbose_name='فعال/غیر فعال')),
                ('is_deleted', models.BooleanField(blank=True, default=False, editable=False, null=True, verbose_name='فعال/غیر فعال')),
            ],
            options={
                'verbose_name': 'آواتار',
                'verbose_name_plural': 'آواتار',
            },
        ),
        migrations.CreateModel(
            name='BookPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='نام فرد')),
                ('last_name', models.CharField(default='', max_length=255, verbose_name='نام خانوادگی فرد')),
                ('phone_number', models.CharField(default='', max_length=13, verbose_name='شماره همراه فرد')),
                ('phone_number_1', models.CharField(blank=True, default='', max_length=13, null=True, verbose_name='شماره تلفن فرد')),
                ('post', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='شغل یا سمت فرد')),
                ('is_deleted', models.BooleanField(blank=True, default=False, editable=False, null=True, verbose_name='فعال/غیر فعال')),
                ('avatar', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='phone_book.avatar', verbose_name='آواتار')),
            ],
            options={
                'verbose_name': 'مخاطب',
                'verbose_name_plural': 'مخاطب',
            },
        ),
        migrations.CreateModel(
            name='BookOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, help_text='مشخص کنید در صورت فعال بودن کاربر مجاز خواهد بود برای خارج کردن از دسترس غیر فعال نمایید', verbose_name='فعال/غیر فعال')),
                ('is_deleted', models.BooleanField(blank=True, default=False, editable=False, null=True, verbose_name='فعال/غیر فعال')),
                ('avatar', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='phone_book.avatar', verbose_name='آواتار')),
                ('user', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'اکانت',
                'verbose_name_plural': 'اکانت',
            },
        ),
        migrations.CreateModel(
            name='Book_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, help_text='مشخص کنید در صورت فعال بودن قابل انتخاب خواهد بود برای خارج کردن از دسترس غیر فعال نمایید', verbose_name='فعال/غیر فعال')),
                ('is_deleted', models.BooleanField(blank=True, default=False, editable=False, null=True, verbose_name='فعال/غیر فعال')),
                ('book_owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='phone_book.bookowner', verbose_name='کاربر')),
                ('book_phone', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='phone_book.bookphone', verbose_name='مخاطب')),
            ],
            options={
                'verbose_name': 'شماره',
                'verbose_name_plural': 'شماره',
            },
        ),
    ]
